data:
  buffer_size: 8192
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  num_conds: 1
  norm_tensor: [[0, 100]]
  train_path: data/compressor/la2a_full_modeling/train
  valid_path: data/compressor/la2a_full_modeling/valid
  test_path: data/compressor/la2a_full_modeling/test
model: 
  arch: concat-gru
  main_rnn_hidden_size: 8
  layer_norm: False
  rnn_bias: True 
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/compressor/test
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 80
  epochs: 200
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 6
  lr: 0.001